arquivo = open("dadosAluno.txt","w")
arquivo.write("\n\nNome do Aluno: Renan Germano \n")
arquivo.write("Matricula do Aluno: 123123123123\n")
arquivo.write("Email do aluno: gitgithub@gmail.com.br\n")
arquivo.write("Data: 04/05/2021                   Hora:08:07 \n")
arquivo.close()

arquivo = open("dadosAluno.txt","r")
print (arquivo.read())
arquivo.close()
